### ISSUE TITLE
UWP: TODO: Fill MediaPlaybackList with full queue

### ISSUE THREAD

**Issue by tekkies** [martijn00/XamarinMediaManager#533]
## 🏗 Enhancement Proposal

Android is able to play an entire playlist but UWP only plays the first item.

### Pitch

There is a TODO in the code already.

### Platforms affected (mark all that apply)
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [X] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
I'm trying to wrap my head around at would could be the best approach. If that would be wrapping the queue in every platform, because iOS also needs an update for this, or if passing around some things would be better.

**Comment by tekkies** [comment]
@martijn00 I think I found a straightforward solution with PR #537
