### ISSUE TITLE
Not able to get the complete meta data (Album Art).

### ISSUE THREAD

**Issue by kishor010** [martijn00/XamarinMediaManager#605]
## 🐛 Bug Report

I am trying to extract meta data through the url.
I was able to fetch meta data for earlier version (Media Manager 0.8.5), but not able to extract complete meta data for the latest version (0.8.8).

It should work for the latest version as well.

url :- Audio URL with metadata.
So for above code I was able to get Album art Image and I was showing it somewhere in my app.
Now In Latest version I am not getting the album art image for the same url.

Can you please tell me is there any other option is available to extract meta data and getting the album art?

1) Writing code to play audio with meta data.

 ```
 var item = await CrossMediaManager.Current.MediaExtractor.CreateMediaItem(url);
  item.MediaType = mediaTypeVal;

```

In above code I was getting album art  **( item.AlbumArt)**  for older version.

**Version:** 1.x

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
Can you test 0.8.9?

**Comment by kishor010** [comment]
@martijn00 
OK fine.
I am getting image now in the latest version but parameter name is different.
